// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4NAB_Dev_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4NAB_Stable_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RegHS_Stable_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RegStudT_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4SAB_Dev_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4SAB_Stable_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4NAB_Dev_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4NAB_Dev_mod, 0},
    {"_rcpp_module_boot_stan_fit4NAB_Stable_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4NAB_Stable_mod, 0},
    {"_rcpp_module_boot_stan_fit4RegHS_Stable_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RegHS_Stable_mod, 0},
    {"_rcpp_module_boot_stan_fit4RegStudT_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RegStudT_mod, 0},
    {"_rcpp_module_boot_stan_fit4SAB_Dev_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4SAB_Dev_mod, 0},
    {"_rcpp_module_boot_stan_fit4SAB_Stable_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4SAB_Stable_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_adaptBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
