// Generated by rstantools.  Do not edit by hand.

/*
    AdaptBayes is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    AdaptBayes is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with AdaptBayes.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_NAB_Dev_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_NAB_Dev");
    reader.add_event(87, 85, "end", "model_NAB_Dev");
    return reader;
}
#include <stan_meta_header.hpp>
class model_NAB_Dev : public prob_grad {
private:
        int n_stan;
        int p_stan;
        int q_stan;
        std::vector<int> y_stan;
        matrix_d x_standardized_stan;
        vector_d alpha_prior_mean_stan;
        matrix_d alpha_prior_cov_stan;
        vector_d sqrt_eigenval_hist_var_stan;
        matrix_d eigenvec_hist_var_stan;
        double local_dof_stan;
        double global_dof_stan;
        double beta_orig_scale_stan;
        double beta_aug_scale_stan;
        double beta_aug_scale_tilde_stan;
        double slab_precision_stan;
        vector_d scale_to_variance225;
        double phi_mean_stan;
        double phi_sd_stan;
        int only_prior;
        vector_d zero_vec;
public:
    model_NAB_Dev(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_NAB_Dev(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_NAB_Dev_namespace::model_NAB_Dev";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "n_stan", "int", context__.to_vec());
            n_stan = int(0);
            vals_i__ = context__.vals_i("n_stan");
            pos__ = 0;
            n_stan = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_stan", n_stan, 1);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "p_stan", "int", context__.to_vec());
            p_stan = int(0);
            vals_i__ = context__.vals_i("p_stan");
            pos__ = 0;
            p_stan = vals_i__[pos__++];
            check_greater_or_equal(function__, "p_stan", p_stan, 1);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "q_stan", "int", context__.to_vec());
            q_stan = int(0);
            vals_i__ = context__.vals_i("q_stan");
            pos__ = 0;
            q_stan = vals_i__[pos__++];
            check_greater_or_equal(function__, "q_stan", q_stan, 0);
            current_statement_begin__ = 6;
            validate_non_negative_index("y_stan", "n_stan", n_stan);
            context__.validate_dims("data initialization", "y_stan", "int", context__.to_vec(n_stan));
            y_stan = std::vector<int>(n_stan, int(0));
            vals_i__ = context__.vals_i("y_stan");
            pos__ = 0;
            size_t y_stan_k_0_max__ = n_stan;
            for (size_t k_0__ = 0; k_0__ < y_stan_k_0_max__; ++k_0__) {
                y_stan[k_0__] = vals_i__[pos__++];
            }
            size_t y_stan_i_0_max__ = n_stan;
            for (size_t i_0__ = 0; i_0__ < y_stan_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "y_stan[i_0__]", y_stan[i_0__], 0);
                check_less_or_equal(function__, "y_stan[i_0__]", y_stan[i_0__], 1);
            }
            current_statement_begin__ = 7;
            validate_non_negative_index("x_standardized_stan", "n_stan", n_stan);
            validate_non_negative_index("x_standardized_stan", "(p_stan + q_stan)", (p_stan + q_stan));
            context__.validate_dims("data initialization", "x_standardized_stan", "matrix_d", context__.to_vec(n_stan,(p_stan + q_stan)));
            x_standardized_stan = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n_stan, (p_stan + q_stan));
            vals_r__ = context__.vals_r("x_standardized_stan");
            pos__ = 0;
            size_t x_standardized_stan_j_2_max__ = (p_stan + q_stan);
            size_t x_standardized_stan_j_1_max__ = n_stan;
            for (size_t j_2__ = 0; j_2__ < x_standardized_stan_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_standardized_stan_j_1_max__; ++j_1__) {
                    x_standardized_stan(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 8;
            validate_non_negative_index("alpha_prior_mean_stan", "p_stan", p_stan);
            context__.validate_dims("data initialization", "alpha_prior_mean_stan", "vector_d", context__.to_vec(p_stan));
            alpha_prior_mean_stan = Eigen::Matrix<double, Eigen::Dynamic, 1>(p_stan);
            vals_r__ = context__.vals_r("alpha_prior_mean_stan");
            pos__ = 0;
            size_t alpha_prior_mean_stan_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < alpha_prior_mean_stan_j_1_max__; ++j_1__) {
                alpha_prior_mean_stan(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("alpha_prior_cov_stan", "p_stan", p_stan);
            validate_non_negative_index("alpha_prior_cov_stan", "p_stan", p_stan);
            context__.validate_dims("data initialization", "alpha_prior_cov_stan", "matrix_d", context__.to_vec(p_stan,p_stan));
            alpha_prior_cov_stan = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p_stan, p_stan);
            vals_r__ = context__.vals_r("alpha_prior_cov_stan");
            pos__ = 0;
            size_t alpha_prior_cov_stan_j_2_max__ = p_stan;
            size_t alpha_prior_cov_stan_j_1_max__ = p_stan;
            for (size_t j_2__ = 0; j_2__ < alpha_prior_cov_stan_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < alpha_prior_cov_stan_j_1_max__; ++j_1__) {
                    alpha_prior_cov_stan(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 10;
            validate_non_negative_index("sqrt_eigenval_hist_var_stan", "p_stan", p_stan);
            context__.validate_dims("data initialization", "sqrt_eigenval_hist_var_stan", "vector_d", context__.to_vec(p_stan));
            sqrt_eigenval_hist_var_stan = Eigen::Matrix<double, Eigen::Dynamic, 1>(p_stan);
            vals_r__ = context__.vals_r("sqrt_eigenval_hist_var_stan");
            pos__ = 0;
            size_t sqrt_eigenval_hist_var_stan_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < sqrt_eigenval_hist_var_stan_j_1_max__; ++j_1__) {
                sqrt_eigenval_hist_var_stan(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("eigenvec_hist_var_stan", "p_stan", p_stan);
            validate_non_negative_index("eigenvec_hist_var_stan", "p_stan", p_stan);
            context__.validate_dims("data initialization", "eigenvec_hist_var_stan", "matrix_d", context__.to_vec(p_stan,p_stan));
            eigenvec_hist_var_stan = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p_stan, p_stan);
            vals_r__ = context__.vals_r("eigenvec_hist_var_stan");
            pos__ = 0;
            size_t eigenvec_hist_var_stan_j_2_max__ = p_stan;
            size_t eigenvec_hist_var_stan_j_1_max__ = p_stan;
            for (size_t j_2__ = 0; j_2__ < eigenvec_hist_var_stan_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < eigenvec_hist_var_stan_j_1_max__; ++j_1__) {
                    eigenvec_hist_var_stan(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "local_dof_stan", "double", context__.to_vec());
            local_dof_stan = double(0);
            vals_r__ = context__.vals_r("local_dof_stan");
            pos__ = 0;
            local_dof_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "local_dof_stan", local_dof_stan, 0);
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "global_dof_stan", "double", context__.to_vec());
            global_dof_stan = double(0);
            vals_r__ = context__.vals_r("global_dof_stan");
            pos__ = 0;
            global_dof_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "global_dof_stan", global_dof_stan, 0);
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "beta_orig_scale_stan", "double", context__.to_vec());
            beta_orig_scale_stan = double(0);
            vals_r__ = context__.vals_r("beta_orig_scale_stan");
            pos__ = 0;
            beta_orig_scale_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "beta_orig_scale_stan", beta_orig_scale_stan, 0);
            current_statement_begin__ = 15;
            context__.validate_dims("data initialization", "beta_aug_scale_stan", "double", context__.to_vec());
            beta_aug_scale_stan = double(0);
            vals_r__ = context__.vals_r("beta_aug_scale_stan");
            pos__ = 0;
            beta_aug_scale_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "beta_aug_scale_stan", beta_aug_scale_stan, 0);
            current_statement_begin__ = 16;
            context__.validate_dims("data initialization", "beta_aug_scale_tilde_stan", "double", context__.to_vec());
            beta_aug_scale_tilde_stan = double(0);
            vals_r__ = context__.vals_r("beta_aug_scale_tilde_stan");
            pos__ = 0;
            beta_aug_scale_tilde_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "beta_aug_scale_tilde_stan", beta_aug_scale_tilde_stan, 0);
            current_statement_begin__ = 17;
            context__.validate_dims("data initialization", "slab_precision_stan", "double", context__.to_vec());
            slab_precision_stan = double(0);
            vals_r__ = context__.vals_r("slab_precision_stan");
            pos__ = 0;
            slab_precision_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "slab_precision_stan", slab_precision_stan, 0);
            current_statement_begin__ = 18;
            validate_non_negative_index("scale_to_variance225", "p_stan", p_stan);
            context__.validate_dims("data initialization", "scale_to_variance225", "vector_d", context__.to_vec(p_stan));
            scale_to_variance225 = Eigen::Matrix<double, Eigen::Dynamic, 1>(p_stan);
            vals_r__ = context__.vals_r("scale_to_variance225");
            pos__ = 0;
            size_t scale_to_variance225_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < scale_to_variance225_j_1_max__; ++j_1__) {
                scale_to_variance225(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "scale_to_variance225", scale_to_variance225, 0);
            current_statement_begin__ = 19;
            context__.validate_dims("data initialization", "phi_mean_stan", "double", context__.to_vec());
            phi_mean_stan = double(0);
            vals_r__ = context__.vals_r("phi_mean_stan");
            pos__ = 0;
            phi_mean_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "phi_mean_stan", phi_mean_stan, 0);
            check_less_or_equal(function__, "phi_mean_stan", phi_mean_stan, 1);
            current_statement_begin__ = 20;
            context__.validate_dims("data initialization", "phi_sd_stan", "double", context__.to_vec());
            phi_sd_stan = double(0);
            vals_r__ = context__.vals_r("phi_sd_stan");
            pos__ = 0;
            phi_sd_stan = vals_r__[pos__++];
            check_greater_or_equal(function__, "phi_sd_stan", phi_sd_stan, 0);
            current_statement_begin__ = 21;
            context__.validate_dims("data initialization", "only_prior", "int", context__.to_vec());
            only_prior = int(0);
            vals_i__ = context__.vals_i("only_prior");
            pos__ = 0;
            only_prior = vals_i__[pos__++];
            check_greater_or_equal(function__, "only_prior", only_prior, 0);
            check_less_or_equal(function__, "only_prior", only_prior, 1);
            // initialize transformed data variables
            current_statement_begin__ = 24;
            validate_non_negative_index("zero_vec", "p_stan", p_stan);
            zero_vec = Eigen::Matrix<double, Eigen::Dynamic, 1>(p_stan);
            stan::math::fill(zero_vec, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 25;
            stan::math::assign(zero_vec, rep_vector(0.0, p_stan));
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 28;
            num_params_r__ += 1;
            current_statement_begin__ = 29;
            validate_non_negative_index("beta_raw_orig", "p_stan", p_stan);
            num_params_r__ += p_stan;
            current_statement_begin__ = 30;
            validate_non_negative_index("beta_raw_aug", "q_stan", q_stan);
            num_params_r__ += q_stan;
            current_statement_begin__ = 31;
            num_params_r__ += 1;
            current_statement_begin__ = 32;
            validate_non_negative_index("lambda_aug_tilde_sq", "q_stan", q_stan);
            num_params_r__ += q_stan;
            current_statement_begin__ = 33;
            num_params_r__ += 1;
            current_statement_begin__ = 34;
            validate_non_negative_index("lambda_orig", "p_stan", p_stan);
            num_params_r__ += p_stan;
            current_statement_begin__ = 35;
            validate_non_negative_index("lambda_aug", "q_stan", q_stan);
            num_params_r__ += q_stan;
            current_statement_begin__ = 36;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_NAB_Dev() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 28;
        if (!(context__.contains_r("mu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu", "double", context__.to_vec());
        double mu(0);
        mu = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 29;
        if (!(context__.contains_r("beta_raw_orig")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_raw_orig missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_raw_orig");
        pos__ = 0U;
        validate_non_negative_index("beta_raw_orig", "p_stan", p_stan);
        context__.validate_dims("parameter initialization", "beta_raw_orig", "vector_d", context__.to_vec(p_stan));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_raw_orig(p_stan);
        size_t beta_raw_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_orig_j_1_max__; ++j_1__) {
            beta_raw_orig(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta_raw_orig);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_raw_orig: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 30;
        if (!(context__.contains_r("beta_raw_aug")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_raw_aug missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_raw_aug");
        pos__ = 0U;
        validate_non_negative_index("beta_raw_aug", "q_stan", q_stan);
        context__.validate_dims("parameter initialization", "beta_raw_aug", "vector_d", context__.to_vec(q_stan));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_raw_aug(q_stan);
        size_t beta_raw_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_aug_j_1_max__; ++j_1__) {
            beta_raw_aug(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta_raw_aug);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_raw_aug: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 31;
        if (!(context__.contains_r("eta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable eta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("eta");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "eta", "double", context__.to_vec());
        double eta(0);
        eta = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, eta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable eta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 32;
        if (!(context__.contains_r("lambda_aug_tilde_sq")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda_aug_tilde_sq missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda_aug_tilde_sq");
        pos__ = 0U;
        validate_non_negative_index("lambda_aug_tilde_sq", "q_stan", q_stan);
        context__.validate_dims("parameter initialization", "lambda_aug_tilde_sq", "vector_d", context__.to_vec(q_stan));
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda_aug_tilde_sq(q_stan);
        size_t lambda_aug_tilde_sq_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_tilde_sq_j_1_max__; ++j_1__) {
            lambda_aug_tilde_sq(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, lambda_aug_tilde_sq);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda_aug_tilde_sq: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 33;
        if (!(context__.contains_r("tau_glob")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable tau_glob missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("tau_glob");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "tau_glob", "double", context__.to_vec());
        double tau_glob(0);
        tau_glob = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, tau_glob);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable tau_glob: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 34;
        if (!(context__.contains_r("lambda_orig")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda_orig missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda_orig");
        pos__ = 0U;
        validate_non_negative_index("lambda_orig", "p_stan", p_stan);
        context__.validate_dims("parameter initialization", "lambda_orig", "vector_d", context__.to_vec(p_stan));
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda_orig(p_stan);
        size_t lambda_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_orig_j_1_max__; ++j_1__) {
            lambda_orig(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, lambda_orig);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda_orig: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 35;
        if (!(context__.contains_r("lambda_aug")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda_aug missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda_aug");
        pos__ = 0U;
        validate_non_negative_index("lambda_aug", "q_stan", q_stan);
        context__.validate_dims("parameter initialization", "lambda_aug", "vector_d", context__.to_vec(q_stan));
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda_aug(q_stan);
        size_t lambda_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_j_1_max__; ++j_1__) {
            lambda_aug(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, lambda_aug);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda_aug: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 36;
        if (!(context__.contains_r("phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "phi", "double", context__.to_vec());
        double phi(0);
        phi = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, phi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable phi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 28;
            local_scalar_t__ mu;
            (void) mu;  // dummy to suppress unused var warning
            if (jacobian__)
                mu = in__.scalar_constrain(lp__);
            else
                mu = in__.scalar_constrain();
            current_statement_begin__ = 29;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_raw_orig;
            (void) beta_raw_orig;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_raw_orig = in__.vector_constrain(p_stan, lp__);
            else
                beta_raw_orig = in__.vector_constrain(p_stan);
            current_statement_begin__ = 30;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_raw_aug;
            (void) beta_raw_aug;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_raw_aug = in__.vector_constrain(q_stan, lp__);
            else
                beta_raw_aug = in__.vector_constrain(q_stan);
            current_statement_begin__ = 31;
            local_scalar_t__ eta;
            (void) eta;  // dummy to suppress unused var warning
            if (jacobian__)
                eta = in__.scalar_lb_constrain(0, lp__);
            else
                eta = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 32;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lambda_aug_tilde_sq;
            (void) lambda_aug_tilde_sq;  // dummy to suppress unused var warning
            if (jacobian__)
                lambda_aug_tilde_sq = in__.vector_lb_constrain(0, q_stan, lp__);
            else
                lambda_aug_tilde_sq = in__.vector_lb_constrain(0, q_stan);
            current_statement_begin__ = 33;
            local_scalar_t__ tau_glob;
            (void) tau_glob;  // dummy to suppress unused var warning
            if (jacobian__)
                tau_glob = in__.scalar_lb_constrain(0, lp__);
            else
                tau_glob = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 34;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lambda_orig;
            (void) lambda_orig;  // dummy to suppress unused var warning
            if (jacobian__)
                lambda_orig = in__.vector_lb_constrain(0, p_stan, lp__);
            else
                lambda_orig = in__.vector_lb_constrain(0, p_stan);
            current_statement_begin__ = 35;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lambda_aug;
            (void) lambda_aug;  // dummy to suppress unused var warning
            if (jacobian__)
                lambda_aug = in__.vector_lb_constrain(0, q_stan, lp__);
            else
                lambda_aug = in__.vector_lb_constrain(0, q_stan);
            current_statement_begin__ = 36;
            local_scalar_t__ phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.scalar_lub_constrain(0, 1, lp__);
            else
                phi = in__.scalar_lub_constrain(0, 1);
            // transformed parameters
            current_statement_begin__ = 39;
            validate_non_negative_index("normalized_beta", "p_stan", p_stan);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> normalized_beta(p_stan);
            stan::math::initialize(normalized_beta, DUMMY_VAR__);
            stan::math::fill(normalized_beta, DUMMY_VAR__);
            current_statement_begin__ = 40;
            validate_non_negative_index("beta_orig", "p_stan", p_stan);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_orig(p_stan);
            stan::math::initialize(beta_orig, DUMMY_VAR__);
            stan::math::fill(beta_orig, DUMMY_VAR__);
            current_statement_begin__ = 41;
            validate_non_negative_index("beta_aug", "q_stan", q_stan);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta_aug(q_stan);
            stan::math::initialize(beta_aug, DUMMY_VAR__);
            stan::math::fill(beta_aug, DUMMY_VAR__);
            current_statement_begin__ = 42;
            validate_non_negative_index("beta", "(p_stan + q_stan)", (p_stan + q_stan));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta((p_stan + q_stan));
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            current_statement_begin__ = 43;
            validate_non_negative_index("theta_orig", "p_stan", p_stan);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> theta_orig(p_stan);
            stan::math::initialize(theta_orig, DUMMY_VAR__);
            stan::math::fill(theta_orig, DUMMY_VAR__);
            current_statement_begin__ = 44;
            validate_non_negative_index("theta_aug", "q_stan", q_stan);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> theta_aug(q_stan);
            stan::math::initialize(theta_aug, DUMMY_VAR__);
            stan::math::fill(theta_aug, DUMMY_VAR__);
            current_statement_begin__ = 45;
            validate_non_negative_index("hist_orig_scale", "p_stan", p_stan);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> hist_orig_scale(p_stan);
            stan::math::initialize(hist_orig_scale, DUMMY_VAR__);
            stan::math::fill(hist_orig_scale, DUMMY_VAR__);
            current_statement_begin__ = 46;
            validate_non_negative_index("normalizing_cov", "p_stan", p_stan);
            validate_non_negative_index("normalizing_cov", "p_stan", p_stan);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> normalizing_cov(p_stan, p_stan);
            stan::math::initialize(normalizing_cov, DUMMY_VAR__);
            stan::math::fill(normalizing_cov, DUMMY_VAR__);
            current_statement_begin__ = 47;
            local_scalar_t__ phi_copy;
            (void) phi_copy;  // dummy to suppress unused var warning
            stan::math::initialize(phi_copy, DUMMY_VAR__);
            stan::math::fill(phi_copy, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 48;
            if (as_bool(logical_gt(phi_sd_stan, 0))) {
                current_statement_begin__ = 49;
                stan::math::assign(phi_copy, phi);
            } else {
                current_statement_begin__ = 51;
                stan::math::assign(phi_copy, phi_mean_stan);
            }
            current_statement_begin__ = 53;
            stan::math::assign(theta_orig, elt_divide(1.0, stan::math::sqrt(add(slab_precision_stan, elt_divide((1 - phi_copy), multiply(pow(tau_glob, 2), square(lambda_orig)))))));
            current_statement_begin__ = 54;
            stan::math::assign(theta_aug, elt_divide(1.0, stan::math::sqrt(add(add(slab_precision_stan, elt_divide((1 - phi_copy), multiply(pow(tau_glob, 2), square(lambda_aug)))), elt_divide(phi_copy, multiply(pow(beta_aug_scale_tilde_stan, 2), lambda_aug_tilde_sq))))));
            current_statement_begin__ = 55;
            stan::math::assign(beta_orig, elt_multiply(theta_orig, beta_raw_orig));
            current_statement_begin__ = 56;
            stan::math::assign(beta_aug, elt_multiply(theta_aug, beta_raw_aug));
            current_statement_begin__ = 57;
            stan::math::assign(beta, append_row(beta_orig, beta_aug));
            current_statement_begin__ = 58;
            stan::math::assign(hist_orig_scale, elt_divide(1.0, stan::math::sqrt(add(multiply(scale_to_variance225, (1 - phi_copy)), (phi_copy / eta)))));
            current_statement_begin__ = 59;
            stan::math::assign(normalizing_cov, quad_form_diag(alpha_prior_cov_stan, hist_orig_scale));
            current_statement_begin__ = 60;
            for (int i = 1; i <= p_stan; ++i) {
                current_statement_begin__ = 61;
                stan::model::assign(normalizing_cov, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            (get_base1(normalizing_cov, i, i, "normalizing_cov", 1) + pow(get_base1(theta_orig, i, "theta_orig", 1), 2)), 
                            "assigning variable normalizing_cov");
            }
            current_statement_begin__ = 63;
            stan::math::assign(normalized_beta, elt_divide(multiply(eigenvec_hist_var_stan, subtract(beta_orig, alpha_prior_mean_stan)), hist_orig_scale));
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 39;
            size_t normalized_beta_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < normalized_beta_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(normalized_beta(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: normalized_beta" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable normalized_beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 40;
            size_t beta_orig_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < beta_orig_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta_orig(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta_orig" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta_orig: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 41;
            size_t beta_aug_j_1_max__ = q_stan;
            for (size_t j_1__ = 0; j_1__ < beta_aug_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta_aug(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta_aug" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta_aug: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 42;
            size_t beta_j_1_max__ = (p_stan + q_stan);
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 43;
            size_t theta_orig_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < theta_orig_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(theta_orig(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: theta_orig" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable theta_orig: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "theta_orig", theta_orig, 0);
            check_less_or_equal(function__, "theta_orig", theta_orig, stan::math::sqrt((1 / slab_precision_stan)));
            current_statement_begin__ = 44;
            size_t theta_aug_j_1_max__ = q_stan;
            for (size_t j_1__ = 0; j_1__ < theta_aug_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(theta_aug(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: theta_aug" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable theta_aug: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "theta_aug", theta_aug, 0);
            check_less_or_equal(function__, "theta_aug", theta_aug, stan::math::sqrt((1 / slab_precision_stan)));
            current_statement_begin__ = 45;
            size_t hist_orig_scale_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < hist_orig_scale_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(hist_orig_scale(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: hist_orig_scale" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable hist_orig_scale: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            check_greater_or_equal(function__, "hist_orig_scale", hist_orig_scale, 0);
            check_less_or_equal(function__, "hist_orig_scale", hist_orig_scale, stan::math::sqrt((1 / min(scale_to_variance225))));
            current_statement_begin__ = 46;
            size_t normalizing_cov_j_1_max__ = p_stan;
            size_t normalizing_cov_j_2_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < normalizing_cov_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < normalizing_cov_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(normalizing_cov(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: normalizing_cov" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable normalizing_cov: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 47;
            if (stan::math::is_uninitialized(phi_copy)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: phi_copy";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable phi_copy: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            check_greater_or_equal(function__, "phi_copy", phi_copy, 0);
            check_less_or_equal(function__, "phi_copy", phi_copy, 1);
            // model body
            current_statement_begin__ = 66;
            lp_accum__.add(normal_log<propto__>(beta_raw_orig, 0.0, 1.0));
            current_statement_begin__ = 67;
            lp_accum__.add(normal_log<propto__>(beta_raw_aug, 0.0, 1.0));
            current_statement_begin__ = 68;
            lp_accum__.add(inv_gamma_log<propto__>(lambda_aug_tilde_sq, 0.5, 0.5));
            current_statement_begin__ = 69;
            lp_accum__.add(inv_gamma_log<propto__>(eta, 25.0, 25.0));
            current_statement_begin__ = 70;
            lp_accum__.add(student_t_log<propto__>(tau_glob, global_dof_stan, 0.0, 1.0));
            current_statement_begin__ = 71;
            lp_accum__.add(student_t_log<propto__>(lambda_orig, local_dof_stan, 0.0, beta_orig_scale_stan));
            current_statement_begin__ = 72;
            lp_accum__.add(student_t_log<propto__>(lambda_aug, local_dof_stan, 0.0, beta_aug_scale_stan));
            current_statement_begin__ = 73;
            lp_accum__.add(logistic_log<propto__>(mu, 0.0, 5.0));
            current_statement_begin__ = 74;
            if (as_bool(logical_gt(phi_sd_stan, 0))) {
                current_statement_begin__ = 75;
                lp_accum__.add(normal_log<propto__>(phi, phi_mean_stan, phi_sd_stan));
            }
            current_statement_begin__ = 78;
            lp_accum__.add(normal_log<propto__>(normalized_beta, 0.0, sqrt_eigenval_hist_var_stan));
            current_statement_begin__ = 80;
            lp_accum__.add(-((1.0 * sum(stan::math::log(hist_orig_scale)))));
            current_statement_begin__ = 82;
            lp_accum__.add(-((1.0 * multi_normal_log(alpha_prior_mean_stan, zero_vec, normalizing_cov))));
            current_statement_begin__ = 83;
            if (as_bool(logical_eq(only_prior, 0))) {
                current_statement_begin__ = 84;
                lp_accum__.add(bernoulli_logit_log<propto__>(y_stan, add(mu, multiply(x_standardized_stan, beta))));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("mu");
        names__.push_back("beta_raw_orig");
        names__.push_back("beta_raw_aug");
        names__.push_back("eta");
        names__.push_back("lambda_aug_tilde_sq");
        names__.push_back("tau_glob");
        names__.push_back("lambda_orig");
        names__.push_back("lambda_aug");
        names__.push_back("phi");
        names__.push_back("normalized_beta");
        names__.push_back("beta_orig");
        names__.push_back("beta_aug");
        names__.push_back("beta");
        names__.push_back("theta_orig");
        names__.push_back("theta_aug");
        names__.push_back("hist_orig_scale");
        names__.push_back("normalizing_cov");
        names__.push_back("phi_copy");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((p_stan + q_stan));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p_stan);
        dims__.push_back(p_stan);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_NAB_Dev_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double mu = in__.scalar_constrain();
        vars__.push_back(mu);
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_raw_orig = in__.vector_constrain(p_stan);
        size_t beta_raw_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_orig_j_1_max__; ++j_1__) {
            vars__.push_back(beta_raw_orig(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta_raw_aug = in__.vector_constrain(q_stan);
        size_t beta_raw_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_aug_j_1_max__; ++j_1__) {
            vars__.push_back(beta_raw_aug(j_1__));
        }
        double eta = in__.scalar_lb_constrain(0);
        vars__.push_back(eta);
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda_aug_tilde_sq = in__.vector_lb_constrain(0, q_stan);
        size_t lambda_aug_tilde_sq_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_tilde_sq_j_1_max__; ++j_1__) {
            vars__.push_back(lambda_aug_tilde_sq(j_1__));
        }
        double tau_glob = in__.scalar_lb_constrain(0);
        vars__.push_back(tau_glob);
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda_orig = in__.vector_lb_constrain(0, p_stan);
        size_t lambda_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_orig_j_1_max__; ++j_1__) {
            vars__.push_back(lambda_orig(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> lambda_aug = in__.vector_lb_constrain(0, q_stan);
        size_t lambda_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_j_1_max__; ++j_1__) {
            vars__.push_back(lambda_aug(j_1__));
        }
        double phi = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(phi);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 39;
            validate_non_negative_index("normalized_beta", "p_stan", p_stan);
            Eigen::Matrix<double, Eigen::Dynamic, 1> normalized_beta(p_stan);
            stan::math::initialize(normalized_beta, DUMMY_VAR__);
            stan::math::fill(normalized_beta, DUMMY_VAR__);
            current_statement_begin__ = 40;
            validate_non_negative_index("beta_orig", "p_stan", p_stan);
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta_orig(p_stan);
            stan::math::initialize(beta_orig, DUMMY_VAR__);
            stan::math::fill(beta_orig, DUMMY_VAR__);
            current_statement_begin__ = 41;
            validate_non_negative_index("beta_aug", "q_stan", q_stan);
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta_aug(q_stan);
            stan::math::initialize(beta_aug, DUMMY_VAR__);
            stan::math::fill(beta_aug, DUMMY_VAR__);
            current_statement_begin__ = 42;
            validate_non_negative_index("beta", "(p_stan + q_stan)", (p_stan + q_stan));
            Eigen::Matrix<double, Eigen::Dynamic, 1> beta((p_stan + q_stan));
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            current_statement_begin__ = 43;
            validate_non_negative_index("theta_orig", "p_stan", p_stan);
            Eigen::Matrix<double, Eigen::Dynamic, 1> theta_orig(p_stan);
            stan::math::initialize(theta_orig, DUMMY_VAR__);
            stan::math::fill(theta_orig, DUMMY_VAR__);
            current_statement_begin__ = 44;
            validate_non_negative_index("theta_aug", "q_stan", q_stan);
            Eigen::Matrix<double, Eigen::Dynamic, 1> theta_aug(q_stan);
            stan::math::initialize(theta_aug, DUMMY_VAR__);
            stan::math::fill(theta_aug, DUMMY_VAR__);
            current_statement_begin__ = 45;
            validate_non_negative_index("hist_orig_scale", "p_stan", p_stan);
            Eigen::Matrix<double, Eigen::Dynamic, 1> hist_orig_scale(p_stan);
            stan::math::initialize(hist_orig_scale, DUMMY_VAR__);
            stan::math::fill(hist_orig_scale, DUMMY_VAR__);
            current_statement_begin__ = 46;
            validate_non_negative_index("normalizing_cov", "p_stan", p_stan);
            validate_non_negative_index("normalizing_cov", "p_stan", p_stan);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> normalizing_cov(p_stan, p_stan);
            stan::math::initialize(normalizing_cov, DUMMY_VAR__);
            stan::math::fill(normalizing_cov, DUMMY_VAR__);
            current_statement_begin__ = 47;
            double phi_copy;
            (void) phi_copy;  // dummy to suppress unused var warning
            stan::math::initialize(phi_copy, DUMMY_VAR__);
            stan::math::fill(phi_copy, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 48;
            if (as_bool(logical_gt(phi_sd_stan, 0))) {
                current_statement_begin__ = 49;
                stan::math::assign(phi_copy, phi);
            } else {
                current_statement_begin__ = 51;
                stan::math::assign(phi_copy, phi_mean_stan);
            }
            current_statement_begin__ = 53;
            stan::math::assign(theta_orig, elt_divide(1.0, stan::math::sqrt(add(slab_precision_stan, elt_divide((1 - phi_copy), multiply(pow(tau_glob, 2), square(lambda_orig)))))));
            current_statement_begin__ = 54;
            stan::math::assign(theta_aug, elt_divide(1.0, stan::math::sqrt(add(add(slab_precision_stan, elt_divide((1 - phi_copy), multiply(pow(tau_glob, 2), square(lambda_aug)))), elt_divide(phi_copy, multiply(pow(beta_aug_scale_tilde_stan, 2), lambda_aug_tilde_sq))))));
            current_statement_begin__ = 55;
            stan::math::assign(beta_orig, elt_multiply(theta_orig, beta_raw_orig));
            current_statement_begin__ = 56;
            stan::math::assign(beta_aug, elt_multiply(theta_aug, beta_raw_aug));
            current_statement_begin__ = 57;
            stan::math::assign(beta, append_row(beta_orig, beta_aug));
            current_statement_begin__ = 58;
            stan::math::assign(hist_orig_scale, elt_divide(1.0, stan::math::sqrt(add(multiply(scale_to_variance225, (1 - phi_copy)), (phi_copy / eta)))));
            current_statement_begin__ = 59;
            stan::math::assign(normalizing_cov, quad_form_diag(alpha_prior_cov_stan, hist_orig_scale));
            current_statement_begin__ = 60;
            for (int i = 1; i <= p_stan; ++i) {
                current_statement_begin__ = 61;
                stan::model::assign(normalizing_cov, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            (get_base1(normalizing_cov, i, i, "normalizing_cov", 1) + pow(get_base1(theta_orig, i, "theta_orig", 1), 2)), 
                            "assigning variable normalizing_cov");
            }
            current_statement_begin__ = 63;
            stan::math::assign(normalized_beta, elt_divide(multiply(eigenvec_hist_var_stan, subtract(beta_orig, alpha_prior_mean_stan)), hist_orig_scale));
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 43;
            check_greater_or_equal(function__, "theta_orig", theta_orig, 0);
            check_less_or_equal(function__, "theta_orig", theta_orig, stan::math::sqrt((1 / slab_precision_stan)));
            current_statement_begin__ = 44;
            check_greater_or_equal(function__, "theta_aug", theta_aug, 0);
            check_less_or_equal(function__, "theta_aug", theta_aug, stan::math::sqrt((1 / slab_precision_stan)));
            current_statement_begin__ = 45;
            check_greater_or_equal(function__, "hist_orig_scale", hist_orig_scale, 0);
            check_less_or_equal(function__, "hist_orig_scale", hist_orig_scale, stan::math::sqrt((1 / min(scale_to_variance225))));
            current_statement_begin__ = 47;
            check_greater_or_equal(function__, "phi_copy", phi_copy, 0);
            check_less_or_equal(function__, "phi_copy", phi_copy, 1);
            // write transformed parameters
            if (include_tparams__) {
                size_t normalized_beta_j_1_max__ = p_stan;
                for (size_t j_1__ = 0; j_1__ < normalized_beta_j_1_max__; ++j_1__) {
                    vars__.push_back(normalized_beta(j_1__));
                }
                size_t beta_orig_j_1_max__ = p_stan;
                for (size_t j_1__ = 0; j_1__ < beta_orig_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_orig(j_1__));
                }
                size_t beta_aug_j_1_max__ = q_stan;
                for (size_t j_1__ = 0; j_1__ < beta_aug_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_aug(j_1__));
                }
                size_t beta_j_1_max__ = (p_stan + q_stan);
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    vars__.push_back(beta(j_1__));
                }
                size_t theta_orig_j_1_max__ = p_stan;
                for (size_t j_1__ = 0; j_1__ < theta_orig_j_1_max__; ++j_1__) {
                    vars__.push_back(theta_orig(j_1__));
                }
                size_t theta_aug_j_1_max__ = q_stan;
                for (size_t j_1__ = 0; j_1__ < theta_aug_j_1_max__; ++j_1__) {
                    vars__.push_back(theta_aug(j_1__));
                }
                size_t hist_orig_scale_j_1_max__ = p_stan;
                for (size_t j_1__ = 0; j_1__ < hist_orig_scale_j_1_max__; ++j_1__) {
                    vars__.push_back(hist_orig_scale(j_1__));
                }
                size_t normalizing_cov_j_2_max__ = p_stan;
                size_t normalizing_cov_j_1_max__ = p_stan;
                for (size_t j_2__ = 0; j_2__ < normalizing_cov_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < normalizing_cov_j_1_max__; ++j_1__) {
                        vars__.push_back(normalizing_cov(j_1__, j_2__));
                    }
                }
                vars__.push_back(phi_copy);
            }
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_NAB_Dev";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_raw_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_orig_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_raw_orig" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_raw_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_aug_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_raw_aug" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "eta";
        param_names__.push_back(param_name_stream__.str());
        size_t lambda_aug_tilde_sq_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_tilde_sq_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_aug_tilde_sq" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau_glob";
        param_names__.push_back(param_name_stream__.str());
        size_t lambda_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_orig_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_orig" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_aug" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t normalized_beta_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < normalized_beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "normalized_beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_orig_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < beta_orig_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_orig" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_aug_j_1_max__ = q_stan;
            for (size_t j_1__ = 0; j_1__ < beta_aug_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_aug" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_j_1_max__ = (p_stan + q_stan);
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t theta_orig_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < theta_orig_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "theta_orig" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t theta_aug_j_1_max__ = q_stan;
            for (size_t j_1__ = 0; j_1__ < theta_aug_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "theta_aug" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t hist_orig_scale_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < hist_orig_scale_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "hist_orig_scale" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t normalizing_cov_j_2_max__ = p_stan;
            size_t normalizing_cov_j_1_max__ = p_stan;
            for (size_t j_2__ = 0; j_2__ < normalizing_cov_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < normalizing_cov_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "normalizing_cov" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi_copy";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        size_t beta_raw_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_orig_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_raw_orig" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_raw_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < beta_raw_aug_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_raw_aug" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "eta";
        param_names__.push_back(param_name_stream__.str());
        size_t lambda_aug_tilde_sq_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_tilde_sq_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_aug_tilde_sq" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau_glob";
        param_names__.push_back(param_name_stream__.str());
        size_t lambda_orig_j_1_max__ = p_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_orig_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_orig" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_aug_j_1_max__ = q_stan;
        for (size_t j_1__ = 0; j_1__ < lambda_aug_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_aug" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t normalized_beta_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < normalized_beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "normalized_beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_orig_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < beta_orig_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_orig" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_aug_j_1_max__ = q_stan;
            for (size_t j_1__ = 0; j_1__ < beta_aug_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_aug" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t beta_j_1_max__ = (p_stan + q_stan);
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t theta_orig_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < theta_orig_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "theta_orig" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t theta_aug_j_1_max__ = q_stan;
            for (size_t j_1__ = 0; j_1__ < theta_aug_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "theta_aug" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t hist_orig_scale_j_1_max__ = p_stan;
            for (size_t j_1__ = 0; j_1__ < hist_orig_scale_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "hist_orig_scale" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t normalizing_cov_j_2_max__ = p_stan;
            size_t normalizing_cov_j_1_max__ = p_stan;
            for (size_t j_2__ = 0; j_2__ < normalizing_cov_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < normalizing_cov_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "normalizing_cov" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi_copy";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_NAB_Dev_namespace::model_NAB_Dev stan_model;
#endif
